package com.hotel.model;

public enum RoomType {
    RESORT_KING,
    RESORT_TWO_QUEEN,
    FOUNTAIN_VIEW_KING,
    FOUNTAIN_VIEW_TWO_QUEEN,
    RESORT_TOWER_KING,
    NEWLY_RENOVATED_PREMIER_TWO_QUEEN,
    NEWLY_RENOVATED_PREMIER_KING,
}